### ISSUE TITLE
Uncaught TypeError: Cannot read property 'geosearch' of undefined

### ISSUE THREAD

**Issue by ScriptedChicken** [MatthewBarker/leaflet-wikipedia#5] opened 2020-12-07 09:38 UTC
Hi there, I'm really enjoying this plugin - always great when you find that someone has thought of exactly what you're looking for!

I'm very new to JS and Leaflet, so this may well be my fault. However, I'm getting an error multiple times when running an app while using this plugin. 

The error: `Uncaught TypeError: Cannot read property 'geosearch' of undefined`

Is this a problem on my end? Thanks in advance!

**Comment by MatthewBarker** [comment] 2024-01-08 21:55
As you can see, this repo isn't maintained often.
The only error I can see in the provided example is that now the Wikipedia API only takes an integer for the radius parameter.
This is fixed in the source and the provided example, but does not fix the reported TypeError that I've been unable to reproduce.

**Closed as completed by MatthewBarker** 2024-01-08 21:55 UTC
